name: master build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"

      - name: Go modules cache
        uses: actions/cache@v1
        with:
          path: /go/pkg
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: make build
